# Список получателей.
# В квадратных скобках: адрес биткоин кошелька, сумма денег и валюта. (usd или btc)
# Все деньги отправляются в btc, если вы указали, к примеру, 10 usd,
# то они будут автоматически конвертированы в btc, согласно текущему курсу.
recipients:
  - [ bitcoin_wallet_address, 10, usd ]
  - [ bitcoin_wallet_address, 0.00015, btc ]

# Комиссия за один байт.
# Можете оставить это поле пустым, тогда комиссия будет рассчитана автоматически,
# исходя из общесреднего значения.
fee: 70

# Приватный ключ кошелька, с которого будет произведён расчёт.
key: your_wallet_private_key